project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!data/"
    - "!README.qmd"

website:
    title: "Issues in MITMA open mobility data"
    site-url: https://e-kotov.github.io/mitma-data-issues
    repo-url: https://github.com/e-kotov/mitma-data-issues
    sidebar:
        tools: 
          - icon: github
            text: Github
            href: https://github.com/e-kotov/mitma-data-issues
        style: "docked"
        search: true
        contents:
        - index.qmd
        - license.qmd
    page-navigation: true
    page-footer: 
      border: true
      left:
       - license.qmd
      center:
        - text: "Egor Kotov"
          href: https://www.ekotov.pro/
      right: 
        - icon: github
          href: https://github.com/e-kotov/mitma-data-issues

bibliography: references.bib

format:
  html:
    include-in-header:
        file: analytics.html
    theme:
      light: zephyr
      dark: slate
    # css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 4
    toc-location: right
    comments:
        utterances:
            repo: e-kotov/mitma-data-issues
            label: comments
            issue-term: pathname
    code-overflow: wrap
    code-fold: false
    code-summary: "Show the code"
    code-tools:
        source: repo
        toggle: true
    grid:
      body-width: 800px
    mermaid:
      theme: neutral

editor: source

editor_options:
  markdown:
    wrap: 72
    canonical: true

